using System.Collections.Generic;

namespace MyTelegramBot
{
    public static class DecisionTable
    {
        public static List<RateRankMapping> GetRateRankMapping()
        {
            return new List<RateRankMapping>
            {
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 44, ToRate = 100, FromRank = 1, ToRank = 3},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 40, ToRate = 43, FromRank = 3,ToRank = 10},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 34, ToRate = 39, FromRank = 10,ToRank = 50},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 31, ToRate = 33, FromRank = 50,ToRank = 90},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 29, ToRate = 31, FromRank = 90,ToRank = 120},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 26, ToRate = 28, FromRank = 120,ToRank = 160},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 23, ToRate = 25, FromRank = 160,ToRank = 200},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 20, ToRate = 22, FromRank = 200,ToRank = 240},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 17, ToRate = 19, FromRank = 240,ToRank = 280},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 14, ToRate = 16, FromRank = 280,ToRank = 300},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 11, ToRate = 13, FromRank = 300,ToRank = 350},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 8, ToRate = 10, FromRank = 350,ToRank = 400},
                new RateRankMapping {MajorType = MajorType.Electronic, FromRate = 5, ToRate = 7, FromRank = 400,ToRank = 450},

                new RateRankMapping {MajorType = MajorType.Control, FromRate = 44, ToRate = 100, FromRank = 1, ToRank = 3},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 40, ToRate = 43, FromRank = 3,ToRank = 10},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 34, ToRate = 39, FromRank = 10,ToRank = 50},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 31, ToRate = 33, FromRank = 50,ToRank = 90},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 29, ToRate = 31, FromRank = 90,ToRank = 120},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 26, ToRate = 28, FromRank = 120,ToRank = 160},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 23, ToRate = 25, FromRank = 160,ToRank = 200},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 20, ToRate = 22, FromRank = 200,ToRank = 240},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 17, ToRate = 19, FromRank = 240,ToRank = 280},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 14, ToRate = 16, FromRank = 280,ToRank = 300},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 11, ToRate = 13, FromRank = 300,ToRank = 350},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 8, ToRate = 10, FromRank = 350,ToRank = 400},
                new RateRankMapping {MajorType = MajorType.Control, FromRate = 5, ToRate = 7, FromRank = 400,ToRank = 450},


                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 44, ToRate = 100, FromRank = 1, ToRank = 3},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 40, ToRate = 43, FromRank = 3,ToRank = 10},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 34, ToRate = 39, FromRank = 10,ToRank = 50},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 31, ToRate = 33, FromRank = 50,ToRank = 90},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 29, ToRate = 31, FromRank = 90,ToRank = 120},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 26, ToRate = 28, FromRank = 120,ToRank = 160},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 23, ToRate = 25, FromRank = 160,ToRank = 200},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 20, ToRate = 22, FromRank = 200,ToRank = 240},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 17, ToRate = 19, FromRank = 240,ToRank = 280},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 14, ToRate = 16, FromRank = 280,ToRank = 300},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 11, ToRate = 13, FromRank = 300,ToRank = 350},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 8, ToRate = 10, FromRank = 350,ToRank = 400},
                new RateRankMapping {MajorType = MajorType.FieldComunication, FromRate = 5, ToRate = 7, FromRank = 400,ToRank = 450},

                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 44, ToRate = 100, FromRank = 1, ToRank = 3},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 40, ToRate = 43, FromRank = 3,ToRank = 10},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 34, ToRate = 39, FromRank = 10,ToRank = 50},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 31, ToRate = 33, FromRank = 50,ToRank = 90},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 29, ToRate = 31, FromRank = 90,ToRank = 120},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 26, ToRate = 28, FromRank = 120,ToRank = 160},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 23, ToRate = 25, FromRank = 160,ToRank = 200},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 20, ToRate = 22, FromRank = 200,ToRank = 240},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 17, ToRate = 19, FromRank = 240,ToRank = 280},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 14, ToRate = 16, FromRank = 280,ToRank = 300},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 11, ToRate = 13, FromRank = 300,ToRank = 350},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 8, ToRate = 10, FromRank = 350,ToRank = 400},
                new RateRankMapping {MajorType = MajorType.Machine, FromRate = 5, ToRate = 7, FromRank = 400,ToRank = 450},

                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 44, ToRate = 100, FromRank = 1, ToRank = 3},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 40, ToRate = 43, FromRank = 3,ToRank = 10},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 34, ToRate = 39, FromRank = 10,ToRank = 50},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 31, ToRate = 33, FromRank = 50,ToRank = 90},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 29, ToRate = 31, FromRank = 90,ToRank = 120},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 26, ToRate = 28, FromRank = 120,ToRank = 160},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 23, ToRate = 25, FromRank = 160,ToRank = 200},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 20, ToRate = 22, FromRank = 200,ToRank = 240},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 17, ToRate = 19, FromRank = 240,ToRank = 280},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 14, ToRate = 16, FromRank = 280,ToRank = 300},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 11, ToRate = 13, FromRank = 300,ToRank = 350},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 8, ToRate = 10, FromRank = 350,ToRank = 400},
                new RateRankMapping {MajorType = MajorType.Mecatronic, FromRate = 5, ToRate = 7, FromRank = 400,ToRank = 450},

                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 44, ToRate = 100, FromRank = 1, ToRank = 3},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 40, ToRate = 43, FromRank = 3,ToRank = 10},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 34, ToRate = 39, FromRank = 10,ToRank = 50},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 31, ToRate = 33, FromRank = 50,ToRank = 90},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 29, ToRate = 31, FromRank = 90,ToRank = 120},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 26, ToRate = 28, FromRank = 120,ToRank = 160},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 23, ToRate = 25, FromRank = 160,ToRank = 200},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 20, ToRate = 22, FromRank = 200,ToRank = 240},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 17, ToRate = 19, FromRank = 240,ToRank = 280},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 14, ToRate = 16, FromRank = 280,ToRank = 300},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 11, ToRate = 13, FromRank = 300,ToRank = 350},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 8, ToRate = 10, FromRank = 350,ToRank = 400},
                new RateRankMapping {MajorType = MajorType.PowerSystems, FromRate = 5, ToRate = 7, FromRank = 400,ToRank = 450},

                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 44, ToRate = 100, FromRank = 1, ToRank = 3},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 40, ToRate = 43, FromRank = 3,ToRank = 10},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 34, ToRate = 39, FromRank = 10,ToRank = 50},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 31, ToRate = 33, FromRank = 50,ToRank = 90},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 29, ToRate = 31, FromRank = 90,ToRank = 120},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 26, ToRate = 28, FromRank = 120,ToRank = 160},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 23, ToRate = 25, FromRank = 160,ToRank = 200},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 20, ToRate = 22, FromRank = 200,ToRank = 240},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 17, ToRate = 19, FromRank = 240,ToRank = 280},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 14, ToRate = 16, FromRank = 280,ToRank = 300},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 11, ToRate = 13, FromRank = 300,ToRank = 350},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 8, ToRate = 10, FromRank = 350,ToRank = 400},
                new RateRankMapping {MajorType = MajorType.SystemComunication, FromRate = 5, ToRate = 7, FromRank = 400,ToRank = 450},

                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 44, ToRate = 100, FromRank = 1, ToRank = 3},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 40, ToRate = 43, FromRank = 3,ToRank = 10},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 34, ToRate = 39, FromRank = 10,ToRank = 50},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 31, ToRate = 33, FromRank = 50,ToRank = 90},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 29, ToRate = 31, FromRank = 90,ToRank = 120},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 26, ToRate = 28, FromRank = 120,ToRank = 160},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 23, ToRate = 25, FromRank = 160,ToRank = 200},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 20, ToRate = 22, FromRank = 200,ToRank = 240},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 17, ToRate = 19, FromRank = 240,ToRank = 280},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 14, ToRate = 16, FromRank = 280,ToRank = 300},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 11, ToRate = 13, FromRank = 300,ToRank = 350},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 8, ToRate = 10, FromRank = 350,ToRank = 400},
                new RateRankMapping {MajorType = MajorType.MedicalEngineering, FromRate = 5, ToRate = 7, FromRank = 400,ToRank = 450},
            };
        }
    }
    
}